version: '3.8'
services:

  prometheus:
    container_name: prometheus_test
    image: prom/prometheus
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    restart: unless-stopped

volumes:
  prometheus:
    external: true
