global:
  scrape_interval: 10s


scrape_configs:
  - job_name: 'temperature-exporter'
    static_configs:
      - targets: ['host.docker.internal:5000']
        labels:
          instance: 'raspberrypi'
          room: 'balcony'

  - job_name: 'node'
    static_configs:
      - targets: [ 'node-exporter:9100' ]