scrape_configs:
  - job_name: 'temperature-exporter'
    scrape_interval: 10s
    static_configs:
    - targets: ['host.docker.internal:5000']
      labels:
        instance: 'raspberrypi'
        room: 'balcony'